[2025-09-13T09:41:20.672+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-13T09:41:20.971+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_intermediate.intermediate.locations.run manual__2025-09-13T09:41:16.265222+00:00 [queued]>
[2025-09-13T09:41:20.996+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_intermediate.intermediate.locations.run manual__2025-09-13T09:41:16.265222+00:00 [queued]>
[2025-09-13T09:41:21.013+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-13T09:41:21.054+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtRunVirtualenvOperator): intermediate.locations.run> on 2025-09-13 09:41:16.265222+00:00
[2025-09-13T09:41:21.072+0000] {standard_task_runner.py:64} INFO - Started process 6355 to run task
[2025-09-13T09:41:21.079+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dbt_intermediate', 'intermediate.locations.run', 'manual__2025-09-13T09:41:16.265222+00:00', '--job-id', '216', '--raw', '--subdir', 'DAGS_FOLDER/dbt_intermediate.py', '--cfg-path', '/tmp/tmpkkom51rz']
[2025-09-13T09:41:21.093+0000] {standard_task_runner.py:91} INFO - Job 216: Subtask intermediate.locations.run
[2025-09-13T09:41:21.788+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_intermediate.intermediate.locations.run manual__2025-09-13T09:41:16.265222+00:00 [running]> on host e95bde6b8d07
[2025-09-13T09:41:22.563+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_intermediate' AIRFLOW_CTX_TASK_ID='intermediate.locations.run' AIRFLOW_CTX_EXECUTION_DATE='2025-09-13T09:41:16.265222+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-13T09:41:16.265222+00:00'
[2025-09-13T09:41:22.566+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-13T09:41:22.590+0000] {virtualenv.py:120} INFO - Checking if the virtualenv lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock exists
[2025-09-13T09:41:22.591+0000] {virtualenv.py:178} INFO - Checking for running process with PID 6351
[2025-09-13T09:41:22.592+0000] {virtualenv.py:181} INFO - Process 6351 running: True and has the lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock.
[2025-09-13T09:41:22.592+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:41:23.594+0000] {virtualenv.py:178} INFO - Checking for running process with PID 6351
[2025-09-13T09:41:23.595+0000] {virtualenv.py:181} INFO - Process 6351 running: True and has the lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock.
[2025-09-13T09:41:23.596+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:41:24.598+0000] {virtualenv.py:178} INFO - Checking for running process with PID 6351
[2025-09-13T09:41:24.599+0000] {virtualenv.py:181} INFO - Process 6351 running: True and has the lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock.
[2025-09-13T09:41:24.600+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:41:25.601+0000] {virtualenv.py:178} INFO - Checking for running process with PID 6351
[2025-09-13T09:41:25.602+0000] {virtualenv.py:181} INFO - Process 6351 running: True and has the lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock.
[2025-09-13T09:41:25.603+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:41:26.604+0000] {virtualenv.py:178} INFO - Checking for running process with PID 6351
[2025-09-13T09:41:26.605+0000] {virtualenv.py:181} INFO - Process 6351 running: True and has the lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock.
[2025-09-13T09:41:26.605+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:41:27.606+0000] {virtualenv.py:178} INFO - Checking for running process with PID 6351
[2025-09-13T09:41:27.607+0000] {virtualenv.py:181} INFO - Process 6351 running: True and has the lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock.
[2025-09-13T09:41:27.607+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:41:28.609+0000] {virtualenv.py:178} INFO - Checking for running process with PID 6351
[2025-09-13T09:41:28.610+0000] {virtualenv.py:181} INFO - Process 6351 running: True and has the lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock.
[2025-09-13T09:41:28.610+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:41:29.612+0000] {virtualenv.py:178} INFO - Checking for running process with PID 6351
[2025-09-13T09:41:29.613+0000] {virtualenv.py:181} INFO - Process 6351 running: True and has the lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock.
[2025-09-13T09:41:29.614+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:41:30.615+0000] {virtualenv.py:178} INFO - Checking for running process with PID 6351
[2025-09-13T09:41:30.616+0000] {virtualenv.py:181} INFO - Process 6351 running: True and has the lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock.
[2025-09-13T09:41:30.617+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:41:31.619+0000] {virtualenv.py:178} INFO - Checking for running process with PID 6351
[2025-09-13T09:41:31.620+0000] {virtualenv.py:181} INFO - Process 6351 running: True and has the lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock.
[2025-09-13T09:41:31.620+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:41:32.622+0000] {virtualenv.py:178} INFO - Checking for running process with PID 6351
[2025-09-13T09:41:32.623+0000] {virtualenv.py:181} INFO - Process 6351 running: True and has the lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock.
[2025-09-13T09:41:32.624+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:41:33.625+0000] {virtualenv.py:178} INFO - Checking for running process with PID 6351
[2025-09-13T09:41:33.626+0000] {virtualenv.py:181} INFO - Process 6351 running: True and has the lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock.
[2025-09-13T09:41:33.626+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:41:34.628+0000] {virtualenv.py:178} INFO - Checking for running process with PID 6351
[2025-09-13T09:41:34.629+0000] {virtualenv.py:181} INFO - Process 6351 running: True and has the lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock.
[2025-09-13T09:41:34.630+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:41:35.632+0000] {virtualenv.py:178} INFO - Checking for running process with PID 6351
[2025-09-13T09:41:35.633+0000] {virtualenv.py:181} INFO - Process 6351 running: True and has the lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock.
[2025-09-13T09:41:35.633+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:41:36.634+0000] {virtualenv.py:131} INFO - Releasing virtualenv lock
[2025-09-13T09:41:36.635+0000] {virtualenv.py:210} WARNING - Lockfile owned by process of pid 6354, while operator has pid 6355
[2025-09-13T09:41:36.636+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-13T09:41:36.637+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/cosmos/operators/virtualenv.py", line 144, in execute
    output = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/cosmos/operators/base.py", line 310, in execute
    self.build_and_run_cmd(context=context, cmd_flags=self.add_cmd_flags())
  File "/home/airflow/.local/lib/python3.10/site-packages/cosmos/operators/local.py", line 853, in build_and_run_cmd
    result = self.run_command(
  File "/home/airflow/.local/lib/python3.10/site-packages/cosmos/operators/virtualenv.py", line 121, in run_command
    while not self._is_lock_available() and self.max_retries_lock:
  File "/home/airflow/.local/lib/python3.10/site-packages/cosmos/operators/virtualenv.py", line 52, in wrapper
    return method(operator, *args)
  File "/home/airflow/.local/lib/python3.10/site-packages/cosmos/operators/virtualenv.py", line 177, in _is_lock_available
    pid = int(lf.read())
ValueError: invalid literal for int() with base 10: ''
[2025-09-13T09:41:36.677+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dbt_intermediate, task_id=intermediate.locations.run, run_id=manual__2025-09-13T09:41:16.265222+00:00, execution_date=20250913T094116, start_date=20250913T094120, end_date=20250913T094136
[2025-09-13T09:41:36.705+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 216 for task intermediate.locations.run (invalid literal for int() with base 10: ''; 6355)
[2025-09-13T09:41:36.720+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-09-13T09:41:36.761+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
