[2025-09-19T10:07:11.800+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-19T10:07:12.060+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_intermediate.intermediate.subcategories_enriched.test manual__2025-09-19T10:00:34.117962+00:00 [queued]>
[2025-09-19T10:07:12.072+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_intermediate.intermediate.subcategories_enriched.test manual__2025-09-19T10:00:34.117962+00:00 [queued]>
[2025-09-19T10:07:12.083+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-19T10:07:12.101+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtTestVirtualenvOperator): intermediate.subcategories_enriched.test> on 2025-09-19 10:00:34.117962+00:00
[2025-09-19T10:07:12.110+0000] {standard_task_runner.py:64} INFO - Started process 2036 to run task
[2025-09-19T10:07:12.115+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dbt_intermediate', 'intermediate.subcategories_enriched.test', 'manual__2025-09-19T10:00:34.117962+00:00', '--job-id', '547', '--raw', '--subdir', 'DAGS_FOLDER/dbt_intermediate.py', '--cfg-path', '/tmp/tmp0psck1sn']
[2025-09-19T10:07:12.119+0000] {standard_task_runner.py:91} INFO - Job 547: Subtask intermediate.subcategories_enriched.test
[2025-09-19T10:07:12.513+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_intermediate.intermediate.subcategories_enriched.test manual__2025-09-19T10:00:34.117962+00:00 [running]> on host e95bde6b8d07
[2025-09-19T10:07:12.906+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_intermediate' AIRFLOW_CTX_TASK_ID='intermediate.subcategories_enriched.test' AIRFLOW_CTX_EXECUTION_DATE='2025-09-19T10:00:34.117962+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-19T10:00:34.117962+00:00'
[2025-09-19T10:07:12.909+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-19T10:07:12.929+0000] {baseoperator.py:400} WARNING - DbtTestVirtualenvOperator.execute cannot be called outside TaskInstance!
[2025-09-19T10:07:12.930+0000] {virtualenv.py:120} INFO - Checking if the virtualenv lock /tmp/cosmos_venv_ecom_intermediate/cosmos_virtualenv.lock exists
[2025-09-19T10:07:12.930+0000] {virtualenv.py:178} INFO - Checking for running process with PID 1822
[2025-09-19T10:07:12.931+0000] {virtualenv.py:181} INFO - Process 1822 running: True and has the lock /tmp/cosmos_venv_ecom_intermediate/cosmos_virtualenv.lock.
[2025-09-19T10:07:12.932+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-19T10:07:13.933+0000] {virtualenv.py:178} INFO - Checking for running process with PID 1611
[2025-09-19T10:07:13.933+0000] {virtualenv.py:181} INFO - Process 1611 running: True and has the lock /tmp/cosmos_venv_ecom_intermediate/cosmos_virtualenv.lock.
[2025-09-19T10:07:13.934+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-19T10:07:14.936+0000] {virtualenv.py:178} INFO - Checking for running process with PID 1611
[2025-09-19T10:07:14.937+0000] {virtualenv.py:181} INFO - Process 1611 running: True and has the lock /tmp/cosmos_venv_ecom_intermediate/cosmos_virtualenv.lock.
[2025-09-19T10:07:14.938+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-19T10:07:15.940+0000] {virtualenv.py:178} INFO - Checking for running process with PID 1611
[2025-09-19T10:07:15.941+0000] {virtualenv.py:181} INFO - Process 1611 running: True and has the lock /tmp/cosmos_venv_ecom_intermediate/cosmos_virtualenv.lock.
[2025-09-19T10:07:15.942+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-19T10:07:16.944+0000] {virtualenv.py:178} INFO - Checking for running process with PID 1611
[2025-09-19T10:07:16.944+0000] {virtualenv.py:181} INFO - Process 1611 running: True and has the lock /tmp/cosmos_venv_ecom_intermediate/cosmos_virtualenv.lock.
[2025-09-19T10:07:16.945+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-19T10:07:17.946+0000] {virtualenv.py:178} INFO - Checking for running process with PID 1611
[2025-09-19T10:07:17.946+0000] {virtualenv.py:181} INFO - Process 1611 running: True and has the lock /tmp/cosmos_venv_ecom_intermediate/cosmos_virtualenv.lock.
[2025-09-19T10:07:17.947+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-19T10:07:18.948+0000] {virtualenv.py:178} INFO - Checking for running process with PID 1611
[2025-09-19T10:07:18.949+0000] {virtualenv.py:181} INFO - Process 1611 running: True and has the lock /tmp/cosmos_venv_ecom_intermediate/cosmos_virtualenv.lock.
[2025-09-19T10:07:18.950+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-19T10:07:19.952+0000] {virtualenv.py:178} INFO - Checking for running process with PID 1611
[2025-09-19T10:07:19.953+0000] {virtualenv.py:181} INFO - Process 1611 running: True and has the lock /tmp/cosmos_venv_ecom_intermediate/cosmos_virtualenv.lock.
[2025-09-19T10:07:19.954+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-19T10:07:20.956+0000] {virtualenv.py:178} INFO - Checking for running process with PID 1611
[2025-09-19T10:07:20.958+0000] {virtualenv.py:181} INFO - Process 1611 running: True and has the lock /tmp/cosmos_venv_ecom_intermediate/cosmos_virtualenv.lock.
[2025-09-19T10:07:20.960+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-19T10:07:21.962+0000] {virtualenv.py:178} INFO - Checking for running process with PID 1611
[2025-09-19T10:07:21.964+0000] {virtualenv.py:181} INFO - Process 1611 running: True and has the lock /tmp/cosmos_venv_ecom_intermediate/cosmos_virtualenv.lock.
[2025-09-19T10:07:21.965+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-19T10:07:22.968+0000] {virtualenv.py:178} INFO - Checking for running process with PID 1611
[2025-09-19T10:07:22.969+0000] {virtualenv.py:181} INFO - Process 1611 running: True and has the lock /tmp/cosmos_venv_ecom_intermediate/cosmos_virtualenv.lock.
[2025-09-19T10:07:22.970+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-19T10:07:23.974+0000] {virtualenv.py:178} INFO - Checking for running process with PID 1611
[2025-09-19T10:07:23.981+0000] {virtualenv.py:181} INFO - Process 1611 running: True and has the lock /tmp/cosmos_venv_ecom_intermediate/cosmos_virtualenv.lock.
[2025-09-19T10:07:23.985+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-19T10:07:24.986+0000] {virtualenv.py:178} INFO - Checking for running process with PID 1611
[2025-09-19T10:07:24.987+0000] {virtualenv.py:181} INFO - Process 1611 running: True and has the lock /tmp/cosmos_venv_ecom_intermediate/cosmos_virtualenv.lock.
[2025-09-19T10:07:24.989+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-19T10:07:25.993+0000] {virtualenv.py:178} INFO - Checking for running process with PID 1611
[2025-09-19T10:07:25.994+0000] {virtualenv.py:181} INFO - Process 1611 running: True and has the lock /tmp/cosmos_venv_ecom_intermediate/cosmos_virtualenv.lock.
[2025-09-19T10:07:25.995+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-19T10:07:26.997+0000] {virtualenv.py:178} INFO - Checking for running process with PID 2123
[2025-09-19T10:07:26.998+0000] {virtualenv.py:181} INFO - Process 2123 running: True and has the lock /tmp/cosmos_venv_ecom_intermediate/cosmos_virtualenv.lock.
[2025-09-19T10:07:26.999+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-19T10:07:27.749+0000] {local_task_job_runner.py:313} WARNING - State of this instance has been externally set to None. Terminating instance.
[2025-09-19T10:07:27.754+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-09-19T10:07:27.756+0000] {process_utils.py:132} INFO - Sending 15 to group 2036. PIDs of all processes in the group: [2036]
[2025-09-19T10:07:27.757+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 2036
[2025-09-19T10:07:27.757+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-09-19T10:07:27.758+0000] {virtualenv.py:131} INFO - Releasing virtualenv lock
[2025-09-19T10:07:27.759+0000] {virtualenv.py:210} WARNING - Lockfile owned by process of pid 2123, while operator has pid 2036
[2025-09-19T10:07:27.759+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-19T10:07:27.812+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/cosmos/operators/virtualenv.py", line 144, in execute
    output = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/cosmos/operators/local.py", line 1089, in execute
    result = self.build_and_run_cmd(context=context, cmd_flags=self.add_cmd_flags())
  File "/home/airflow/.local/lib/python3.10/site-packages/cosmos/operators/local.py", line 853, in build_and_run_cmd
    result = self.run_command(
  File "/home/airflow/.local/lib/python3.10/site-packages/cosmos/operators/virtualenv.py", line 123, in run_command
    time.sleep(1)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2613, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2025-09-19T10:07:27.817+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dbt_intermediate, task_id=intermediate.subcategories_enriched.test, run_id=manual__2025-09-19T10:00:34.117962+00:00, execution_date=20250919T100034, start_date=20250919T100712, end_date=20250919T100727
[2025-09-19T10:07:27.838+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 547 for task intermediate.subcategories_enriched.test ((psycopg2.errors.ForeignKeyViolation) insert or update on table "task_fail" violates foreign key constraint "task_fail_ti_fkey"
DETAIL:  Key (dag_id, task_id, run_id, map_index)=(dbt_intermediate, intermediate.subcategories_enriched.test, manual__2025-09-19T10:00:34.117962+00:00, -1) is not present in table "task_instance".

[SQL: INSERT INTO task_fail (task_id, dag_id, run_id, map_index, start_date, end_date, duration) VALUES (%(task_id)s, %(dag_id)s, %(run_id)s, %(map_index)s, %(start_date)s, %(end_date)s, %(duration)s) RETURNING task_fail.id]
[parameters: {'task_id': 'intermediate.subcategories_enriched.test', 'dag_id': 'dbt_intermediate', 'run_id': 'manual__2025-09-19T10:00:34.117962+00:00', 'map_index': -1, 'start_date': datetime.datetime(2025, 9, 19, 10, 7, 12, 60961, tzinfo=Timezone('UTC')), 'end_date': datetime.datetime(2025, 9, 19, 10, 7, 27, 816923, tzinfo=Timezone('UTC')), 'duration': 15}]
(Background on this error at: https://sqlalche.me/e/14/gkpj); 2036)
[2025-09-19T10:07:27.890+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=2036, status='terminated', exitcode=1, started='10:07:12') (2036) terminated with exit code 1
