[2025-09-13T09:41:05.808+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-13T09:41:05.992+0000] {taskinstance.py:2066} INFO - Dependencies not met for <TaskInstance: dbt_marts.marts.fct_customer_activity.run manual__2025-09-13T09:40:29.757092+00:00 [failed]>, dependency 'Task Instance State' FAILED: Task is in the 'failed' state.
[2025-09-13T09:41:06.008+0000] {local_task_job_runner.py:163} INFO - Task is not able to be run
