[2025-09-13T09:41:04.420+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-13T09:41:04.625+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_marts.marts.fct_customer_reviews.run manual__2025-09-13T09:40:29.757092+00:00 [queued]>
[2025-09-13T09:41:04.658+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_marts.marts.fct_customer_reviews.run manual__2025-09-13T09:40:29.757092+00:00 [queued]>
[2025-09-13T09:41:04.662+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-13T09:41:04.874+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtRunVirtualenvOperator): marts.fct_customer_reviews.run> on 2025-09-13 09:40:29.757092+00:00
[2025-09-13T09:41:04.883+0000] {standard_task_runner.py:64} INFO - Started process 6304 to run task
[2025-09-13T09:41:04.891+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dbt_marts', 'marts.fct_customer_reviews.run', 'manual__2025-09-13T09:40:29.757092+00:00', '--job-id', '204', '--raw', '--subdir', 'DAGS_FOLDER/dbt_marts.py', '--cfg-path', '/tmp/tmpnzf7xjau']
[2025-09-13T09:41:04.895+0000] {standard_task_runner.py:91} INFO - Job 204: Subtask marts.fct_customer_reviews.run
[2025-09-13T09:41:05.476+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_marts.marts.fct_customer_reviews.run manual__2025-09-13T09:40:29.757092+00:00 [running]> on host e95bde6b8d07
[2025-09-13T09:41:06.353+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_marts' AIRFLOW_CTX_TASK_ID='marts.fct_customer_reviews.run' AIRFLOW_CTX_EXECUTION_DATE='2025-09-13T09:40:29.757092+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-13T09:40:29.757092+00:00'
[2025-09-13T09:41:06.357+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-13T09:41:06.383+0000] {virtualenv.py:120} INFO - Checking if the virtualenv lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock exists
[2025-09-13T09:41:06.384+0000] {virtualenv.py:178} INFO - Checking for running process with PID 6194
[2025-09-13T09:41:06.385+0000] {virtualenv.py:181} INFO - Process 6194 running: True and has the lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock.
[2025-09-13T09:41:06.386+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:41:07.384+0000] {virtualenv.py:178} INFO - Checking for running process with PID 6194
[2025-09-13T09:41:07.388+0000] {virtualenv.py:181} INFO - Process 6194 running: True and has the lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock.
[2025-09-13T09:41:07.389+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:41:08.391+0000] {virtualenv.py:178} INFO - Checking for running process with PID 6194
[2025-09-13T09:41:08.392+0000] {virtualenv.py:181} INFO - Process 6194 running: True and has the lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock.
[2025-09-13T09:41:08.393+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:41:09.395+0000] {virtualenv.py:178} INFO - Checking for running process with PID 6194
[2025-09-13T09:41:09.396+0000] {virtualenv.py:181} INFO - Process 6194 running: True and has the lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock.
[2025-09-13T09:41:09.397+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:41:10.398+0000] {virtualenv.py:178} INFO - Checking for running process with PID 6194
[2025-09-13T09:41:10.399+0000] {virtualenv.py:181} INFO - Process 6194 running: True and has the lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock.
[2025-09-13T09:41:10.399+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:41:11.400+0000] {virtualenv.py:178} INFO - Checking for running process with PID 6194
[2025-09-13T09:41:11.401+0000] {virtualenv.py:181} INFO - Process 6194 running: True and has the lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock.
[2025-09-13T09:41:11.402+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:41:12.403+0000] {virtualenv.py:178} INFO - Checking for running process with PID 6194
[2025-09-13T09:41:12.404+0000] {virtualenv.py:181} INFO - Process 6194 running: True and has the lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock.
[2025-09-13T09:41:12.404+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:41:13.406+0000] {virtualenv.py:178} INFO - Checking for running process with PID 6194
[2025-09-13T09:41:13.406+0000] {virtualenv.py:181} INFO - Process 6194 running: True and has the lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock.
[2025-09-13T09:41:13.407+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:41:14.408+0000] {virtualenv.py:178} INFO - Checking for running process with PID 6194
[2025-09-13T09:41:14.409+0000] {virtualenv.py:181} INFO - Process 6194 running: True and has the lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock.
[2025-09-13T09:41:14.410+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:41:15.303+0000] {local_task_job_runner.py:313} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-09-13T09:41:15.304+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-09-13T09:41:15.307+0000] {process_utils.py:132} INFO - Sending 15 to group 6304. PIDs of all processes in the group: [6304]
[2025-09-13T09:41:15.307+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 6304
[2025-09-13T09:41:15.308+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-09-13T09:41:15.309+0000] {virtualenv.py:131} INFO - Releasing virtualenv lock
[2025-09-13T09:41:15.309+0000] {virtualenv.py:210} WARNING - Lockfile owned by process of pid 6194, while operator has pid 6304
[2025-09-13T09:41:15.310+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-13T09:41:15.443+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=6304, status='terminated', exitcode=0, started='09:41:04') (6304) terminated with exit code 0
