[2025-09-13T09:41:39.653+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-13T09:41:39.699+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_intermediate.intermediate.customer_interactions.test manual__2025-09-13T09:41:16.265222+00:00 [queued]>
[2025-09-13T09:41:39.710+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_intermediate.intermediate.customer_interactions.test manual__2025-09-13T09:41:16.265222+00:00 [queued]>
[2025-09-13T09:41:39.721+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-13T09:41:39.738+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtTestVirtualenvOperator): intermediate.customer_interactions.test> on 2025-09-13 09:41:16.265222+00:00
[2025-09-13T09:41:39.744+0000] {standard_task_runner.py:64} INFO - Started process 6444 to run task
[2025-09-13T09:41:39.747+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dbt_intermediate', 'intermediate.customer_interactions.test', 'manual__2025-09-13T09:41:16.265222+00:00', '--job-id', '220', '--raw', '--subdir', 'DAGS_FOLDER/dbt_intermediate.py', '--cfg-path', '/tmp/tmpab_64fpw']
[2025-09-13T09:41:39.750+0000] {standard_task_runner.py:91} INFO - Job 220: Subtask intermediate.customer_interactions.test
[2025-09-13T09:41:39.889+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_intermediate.intermediate.customer_interactions.test manual__2025-09-13T09:41:16.265222+00:00 [running]> on host e95bde6b8d07
[2025-09-13T09:41:40.108+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_intermediate' AIRFLOW_CTX_TASK_ID='intermediate.customer_interactions.test' AIRFLOW_CTX_EXECUTION_DATE='2025-09-13T09:41:16.265222+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-13T09:41:16.265222+00:00'
[2025-09-13T09:41:40.110+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-13T09:41:40.130+0000] {baseoperator.py:400} WARNING - DbtTestVirtualenvOperator.execute cannot be called outside TaskInstance!
[2025-09-13T09:41:40.158+0000] {virtualenv.py:120} INFO - Checking if the virtualenv lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock exists
[2025-09-13T09:41:40.159+0000] {virtualenv.py:178} INFO - Checking for running process with PID 6354
[2025-09-13T09:41:40.162+0000] {virtualenv.py:181} INFO - Process 6354 running: True and has the lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock.
[2025-09-13T09:41:40.163+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:41:41.165+0000] {virtualenv.py:178} INFO - Checking for running process with PID 6354
[2025-09-13T09:41:41.166+0000] {virtualenv.py:181} INFO - Process 6354 running: True and has the lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock.
[2025-09-13T09:41:41.166+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:41:42.167+0000] {virtualenv.py:178} INFO - Checking for running process with PID 6354
[2025-09-13T09:41:42.169+0000] {virtualenv.py:181} INFO - Process 6354 running: True and has the lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock.
[2025-09-13T09:41:42.169+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:41:43.171+0000] {virtualenv.py:178} INFO - Checking for running process with PID 6354
[2025-09-13T09:41:43.172+0000] {virtualenv.py:181} INFO - Process 6354 running: True and has the lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock.
[2025-09-13T09:41:43.173+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:41:44.175+0000] {virtualenv.py:178} INFO - Checking for running process with PID 6354
[2025-09-13T09:41:44.175+0000] {virtualenv.py:181} INFO - Process 6354 running: True and has the lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock.
[2025-09-13T09:41:44.176+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:41:45.177+0000] {virtualenv.py:178} INFO - Checking for running process with PID 6354
[2025-09-13T09:41:45.178+0000] {virtualenv.py:181} INFO - Process 6354 running: True and has the lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock.
[2025-09-13T09:41:45.179+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:41:46.180+0000] {virtualenv.py:178} INFO - Checking for running process with PID 6354
[2025-09-13T09:41:46.181+0000] {virtualenv.py:181} INFO - Process 6354 running: True and has the lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock.
[2025-09-13T09:41:46.181+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:41:47.182+0000] {virtualenv.py:178} INFO - Checking for running process with PID 6354
[2025-09-13T09:41:47.183+0000] {virtualenv.py:181} INFO - Process 6354 running: True and has the lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock.
[2025-09-13T09:41:47.183+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:41:48.185+0000] {virtualenv.py:178} INFO - Checking for running process with PID 6354
[2025-09-13T09:41:48.194+0000] {virtualenv.py:181} INFO - Process 6354 running: True and has the lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock.
[2025-09-13T09:41:48.210+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:41:49.212+0000] {virtualenv.py:178} INFO - Checking for running process with PID 6354
[2025-09-13T09:41:49.213+0000] {virtualenv.py:181} INFO - Process 6354 running: True and has the lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock.
[2025-09-13T09:41:49.214+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:41:50.215+0000] {virtualenv.py:126} INFO - Acquiring the virtualenv lock
[2025-09-13T09:41:50.216+0000] {virtualenv.py:195} INFO - Acquiring lock at /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock with pid 6444
[2025-09-13T09:41:50.217+0000] {virtualenv.py:153} INFO - Creating or updating the virtualenv at `/tmp/cosmos_venv_ecom
[2025-09-13T09:41:50.217+0000] {process_utils.py:183} INFO - Executing cmd: /home/***/.local/bin/python -m virtualenv /tmp/cosmos_venv_ecom --python=python3
[2025-09-13T09:41:50.218+0000] {process_utils.py:187} INFO - Output:
[2025-09-13T09:41:51.791+0000] {process_utils.py:191} INFO - created virtual environment CPython3.10.14.final.0-64 in 736ms
[2025-09-13T09:41:51.792+0000] {process_utils.py:191} INFO -   creator CPython3Posix(dest=/tmp/cosmos_venv_ecom, clear=False, no_vcs_ignore=False, global=False)
[2025-09-13T09:41:51.793+0000] {process_utils.py:191} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2025-09-13T09:41:51.795+0000] {process_utils.py:191} INFO -     added seed packages: MarkupSafe==3.0.2, PyYAML==6.0.2, agate==1.9.1, annotated_types==0.7.0, attrs==25.3.0, babel==2.17.0, certifi==2025.8.3, charset_normalizer==3.4.3, click==8.2.1, clickhouse_connect==0.8.18, clickhouse_driver==0.2.9, colorama==0.4.6, daff==1.4.2, dbt_adapters==1.16.7, dbt_clickhouse==1.9.3, dbt_common==1.30.0, dbt_core==1.10.11, dbt_extractor==0.6.0, dbt_protos==1.0.375, dbt_semantic_interfaces==0.9.0, deepdiff==8.6.1, idna==3.10, importlib_metadata==8.7.0, isodate==0.6.1, jinja2==3.1.6, jsonschema==4.25.1, jsonschema_specifications==2025.9.1, leather==0.4.0, lz4==4.4.4, mashumaro==3.14, more_itertools==10.8.0, msgpack==1.1.1, networkx==3.4.2, orderly_set==5.5.0, packaging==25.0, parsedatetime==2.6, pathspec==0.12.1, pip==25.2, protobuf==6.32.1, pydantic==2.11.7, pydantic_core==2.33.2, python_dateutil==2.9.0.post0, python_slugify==8.0.4, pytimeparse==1.1.8, pytz==2025.2, referencing==0.36.2, requests==2.32.5, rpds_py==0.27.1, setuptools==80.9.0, six==1.17.0, snowplow_tracker==1.1.0, sqlparse==0.5.3, text_unidecode==1.3, typing_extensions==4.15.0, typing_inspection==0.4.1, tzlocal==5.3.1, urllib3==2.5.0, wheel==0.45.1, zipp==3.23.0, zstandard==0.24.0
[2025-09-13T09:41:51.796+0000] {process_utils.py:191} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2025-09-13T09:41:51.885+0000] {process_utils.py:183} INFO - Executing cmd: /tmp/cosmos_venv_ecom/bin/pip install dbt-clickhouse
[2025-09-13T09:41:51.887+0000] {process_utils.py:187} INFO - Output:
[2025-09-13T09:41:52.921+0000] {process_utils.py:191} INFO - Traceback (most recent call last):
[2025-09-13T09:41:52.922+0000] {process_utils.py:191} INFO -   File "/tmp/cosmos_venv_ecom/bin/pip", line 8, in <module>
[2025-09-13T09:41:52.922+0000] {process_utils.py:191} INFO -   File "/tmp/cosmos_venv_ecom/lib/python3.10/site-packages/pip/_internal/cli/main.py", line 78, in main
[2025-09-13T09:41:52.923+0000] {process_utils.py:191} INFO -     command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
[2025-09-13T09:41:52.923+0000] {process_utils.py:191} INFO -   File "/tmp/cosmos_venv_ecom/lib/python3.10/site-packages/pip/_internal/commands/__init__.py", line 121, in create_command
[2025-09-13T09:41:52.924+0000] {process_utils.py:191} INFO -     module = importlib.import_module(module_path)
[2025-09-13T09:41:52.924+0000] {process_utils.py:191} INFO -   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
[2025-09-13T09:41:52.924+0000] {process_utils.py:191} INFO -     return _bootstrap._gcd_import(name[level:], package, level)
[2025-09-13T09:41:52.925+0000] {process_utils.py:191} INFO -   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
[2025-09-13T09:41:52.925+0000] {process_utils.py:191} INFO -   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
[2025-09-13T09:41:52.926+0000] {process_utils.py:191} INFO -   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
[2025-09-13T09:41:52.926+0000] {process_utils.py:191} INFO -   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
[2025-09-13T09:41:52.926+0000] {process_utils.py:191} INFO -   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
[2025-09-13T09:41:52.927+0000] {process_utils.py:191} INFO -   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
[2025-09-13T09:41:52.927+0000] {process_utils.py:191} INFO -   File "/tmp/cosmos_venv_ecom/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 22, in <module>
[2025-09-13T09:41:52.928+0000] {process_utils.py:191} INFO -     import pip._internal.self_outdated_check  # noqa: F401
[2025-09-13T09:41:52.928+0000] {process_utils.py:191} INFO -   File "/tmp/cosmos_venv_ecom/lib/python3.10/site-packages/pip/_internal/self_outdated_check.py", line 20, in <module>
[2025-09-13T09:41:52.929+0000] {process_utils.py:191} INFO -     from pip._internal.index.collector import LinkCollector
[2025-09-13T09:41:52.929+0000] {process_utils.py:191} INFO -   File "/tmp/cosmos_venv_ecom/lib/python3.10/site-packages/pip/_internal/index/collector.py", line 33, in <module>
[2025-09-13T09:41:52.929+0000] {process_utils.py:191} INFO -     from pip._internal.network.session import PipSession
[2025-09-13T09:41:52.930+0000] {process_utils.py:191} INFO -   File "/tmp/cosmos_venv_ecom/lib/python3.10/site-packages/pip/_internal/network/session.py", line 30, in <module>
[2025-09-13T09:41:52.930+0000] {process_utils.py:191} INFO -     from pip._vendor.cachecontrol import CacheControlAdapter as _BaseCacheControlAdapter
[2025-09-13T09:41:52.931+0000] {process_utils.py:191} INFO - ModuleNotFoundError: No module named 'pip._vendor.cachecontrol'
[2025-09-13T09:41:52.979+0000] {virtualenv.py:131} INFO - Releasing virtualenv lock
[2025-09-13T09:41:52.980+0000] {virtualenv.py:210} WARNING - Lockfile owned by process of pid 6352, while operator has pid 6444
[2025-09-13T09:41:52.982+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-13T09:41:52.983+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/cosmos/operators/virtualenv.py", line 144, in execute
    output = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/cosmos/operators/local.py", line 1089, in execute
    result = self.build_and_run_cmd(context=context, cmd_flags=self.add_cmd_flags())
  File "/home/airflow/.local/lib/python3.10/site-packages/cosmos/operators/local.py", line 853, in build_and_run_cmd
    result = self.run_command(
  File "/home/airflow/.local/lib/python3.10/site-packages/cosmos/operators/virtualenv.py", line 128, in run_command
    self._py_bin = self._prepare_virtualenv()
  File "/home/airflow/.local/lib/python3.10/site-packages/cosmos/operators/virtualenv.py", line 154, in _prepare_virtualenv
    py_bin = prepare_virtualenv(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/python_virtualenv.py", line 119, in prepare_virtualenv
    execute_in_subprocess(pip_cmd)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/process_utils.py", line 172, in execute_in_subprocess
    execute_in_subprocess_with_kwargs(cmd, cwd=cwd)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/process_utils.py", line 195, in execute_in_subprocess_with_kwargs
    raise subprocess.CalledProcessError(exit_code, cmd)
subprocess.CalledProcessError: Command '['/tmp/cosmos_venv_ecom/bin/pip', 'install', 'dbt-clickhouse']' returned non-zero exit status 1.
[2025-09-13T09:41:53.047+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dbt_intermediate, task_id=intermediate.customer_interactions.test, run_id=manual__2025-09-13T09:41:16.265222+00:00, execution_date=20250913T094116, start_date=20250913T094139, end_date=20250913T094153
[2025-09-13T09:41:53.079+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 220 for task intermediate.customer_interactions.test (Command '['/tmp/cosmos_venv_ecom/bin/pip', 'install', 'dbt-clickhouse']' returned non-zero exit status 1.; 6444)
[2025-09-13T09:41:53.119+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-09-13T09:41:53.194+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-13T09:41:53.199+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
